/* Generated by Yosys 0.68+ (git sha1 a5af9d690, Release, GNU /usr/bin/c++ 13.3.0) [github.com/The-OpenROAD-Project/yosys at HEAD] */

(* top =  1  *)
(* src = "ripple_adder.v:1.1-11.10" *)
module ripple_adder(a, b, cin, sum, cout);
  (* src = "ripple_adder.v:2.18-2.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "ripple_adder.v:3.18-3.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "ripple_adder.v:4.18-4.21" *)
  input cin;
  wire cin;
  (* src = "ripple_adder.v:5.18-5.21" *)
  output [3:0] sum;
  wire [3:0] sum;
  (* src = "ripple_adder.v:6.18-6.22" *)
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  assign _00_ = ~(a[3] & b[3]);
  assign _01_ = ~(a[2] & b[2]);
  assign _02_ = ~(a[1] & b[1]);
  assign _03_ = ~(a[0] & b[0]);
  assign _04_ = a[0] ^ b[0];
  assign _05_ = ~(cin & _04_);
  assign _06_ = ~(_03_ & _05_);
  assign _07_ = a[1] ^ b[1];
  assign _08_ = ~(_06_ & _07_);
  assign _09_ = ~(_02_ & _08_);
  assign _10_ = a[2] ^ b[2];
  assign _11_ = ~(_09_ & _10_);
  assign _12_ = ~(_01_ & _11_);
  assign _13_ = a[3] ^ b[3];
  assign _14_ = ~(_12_ & _13_);
  assign cout = ~(_00_ & _14_);
  assign sum[3] = _12_ ^ _13_;
  assign sum[2] = _09_ ^ _10_;
  assign sum[1] = _06_ ^ _07_;
  assign sum[0] = cin ^ _04_;
endmodule
